/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SssRouteImport } from './routes/sss'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResimSikistirRouteImport } from './routes/resim-sikistir'
import { Route as PdfSikistirRouteImport } from './routes/pdf-sikistir'
import { Route as PdfBirlestirRouteImport } from './routes/pdf-birlestir'
import { Route as OzelliklerimizRouteImport } from './routes/ozelliklerimiz'
import { Route as NasilKullanilirRouteImport } from './routes/nasil-kullanilir'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GuvenlikRouteImport } from './routes/guvenlik'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'

const SssRoute = SssRouteImport.update({
  id: '/sss',
  path: '/sss',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResimSikistirRoute = ResimSikistirRouteImport.update({
  id: '/resim-sikistir',
  path: '/resim-sikistir',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfSikistirRoute = PdfSikistirRouteImport.update({
  id: '/pdf-sikistir',
  path: '/pdf-sikistir',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfBirlestirRoute = PdfBirlestirRouteImport.update({
  id: '/pdf-birlestir',
  path: '/pdf-birlestir',
  getParentRoute: () => rootRouteImport,
} as any)
const OzelliklerimizRoute = OzelliklerimizRouteImport.update({
  id: '/ozelliklerimiz',
  path: '/ozelliklerimiz',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilKullanilirRoute = NasilKullanilirRouteImport.update({
  id: '/nasil-kullanilir',
  path: '/nasil-kullanilir',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GuvenlikRoute = GuvenlikRouteImport.update({
  id: '/guvenlik',
  path: '/guvenlik',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/guvenlik': typeof GuvenlikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/nasil-kullanilir': typeof NasilKullanilirRoute
  '/ozelliklerimiz': typeof OzelliklerimizRoute
  '/pdf-birlestir': typeof PdfBirlestirRoute
  '/pdf-sikistir': typeof PdfSikistirRoute
  '/resim-sikistir': typeof ResimSikistirRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/guvenlik': typeof GuvenlikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/nasil-kullanilir': typeof NasilKullanilirRoute
  '/ozelliklerimiz': typeof OzelliklerimizRoute
  '/pdf-birlestir': typeof PdfBirlestirRoute
  '/pdf-sikistir': typeof PdfSikistirRoute
  '/resim-sikistir': typeof ResimSikistirRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/guvenlik': typeof GuvenlikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/nasil-kullanilir': typeof NasilKullanilirRoute
  '/ozelliklerimiz': typeof OzelliklerimizRoute
  '/pdf-birlestir': typeof PdfBirlestirRoute
  '/pdf-sikistir': typeof PdfSikistirRoute
  '/resim-sikistir': typeof ResimSikistirRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/gizlilik-politikasi'
    | '/guvenlik'
    | '/hakkimizda'
    | '/iletisim'
    | '/nasil-kullanilir'
    | '/ozelliklerimiz'
    | '/pdf-birlestir'
    | '/pdf-sikistir'
    | '/resim-sikistir'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/gizlilik-politikasi'
    | '/guvenlik'
    | '/hakkimizda'
    | '/iletisim'
    | '/nasil-kullanilir'
    | '/ozelliklerimiz'
    | '/pdf-birlestir'
    | '/pdf-sikistir'
    | '/resim-sikistir'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sss'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/gizlilik-politikasi'
    | '/guvenlik'
    | '/hakkimizda'
    | '/iletisim'
    | '/nasil-kullanilir'
    | '/ozelliklerimiz'
    | '/pdf-birlestir'
    | '/pdf-sikistir'
    | '/resim-sikistir'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  GuvenlikRoute: typeof GuvenlikRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  NasilKullanilirRoute: typeof NasilKullanilirRoute
  OzelliklerimizRoute: typeof OzelliklerimizRoute
  PdfBirlestirRoute: typeof PdfBirlestirRoute
  PdfSikistirRoute: typeof PdfSikistirRoute
  ResimSikistirRoute: typeof ResimSikistirRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SssRoute: typeof SssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sss': {
      id: '/sss'
      path: '/sss'
      fullPath: '/sss'
      preLoaderRoute: typeof SssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resim-sikistir': {
      id: '/resim-sikistir'
      path: '/resim-sikistir'
      fullPath: '/resim-sikistir'
      preLoaderRoute: typeof ResimSikistirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-sikistir': {
      id: '/pdf-sikistir'
      path: '/pdf-sikistir'
      fullPath: '/pdf-sikistir'
      preLoaderRoute: typeof PdfSikistirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-birlestir': {
      id: '/pdf-birlestir'
      path: '/pdf-birlestir'
      fullPath: '/pdf-birlestir'
      preLoaderRoute: typeof PdfBirlestirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ozelliklerimiz': {
      id: '/ozelliklerimiz'
      path: '/ozelliklerimiz'
      fullPath: '/ozelliklerimiz'
      preLoaderRoute: typeof OzelliklerimizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-kullanilir': {
      id: '/nasil-kullanilir'
      path: '/nasil-kullanilir'
      fullPath: '/nasil-kullanilir'
      preLoaderRoute: typeof NasilKullanilirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guvenlik': {
      id: '/guvenlik'
      path: '/guvenlik'
      fullPath: '/guvenlik'
      preLoaderRoute: typeof GuvenlikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  GuvenlikRoute: GuvenlikRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  NasilKullanilirRoute: NasilKullanilirRoute,
  OzelliklerimizRoute: OzelliklerimizRoute,
  PdfBirlestirRoute: PdfBirlestirRoute,
  PdfSikistirRoute: PdfSikistirRoute,
  ResimSikistirRoute: ResimSikistirRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SssRoute: SssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
